version: "3"
services:
  broker:
    container_name: broker
    networks:
      - broker
    image: "docker.io/bitnami/rabbitmq:latest"
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - ${RABBITMQ_DATA_DIR}:/bitnami

networks:
  broker:
    driver: bridge