receivers:
 jaeger:
   protocols:
     thrift_compact:

processors:
 batch:

exporters:
 otlp:
   endpoint: tempo-us-central1.grafana.net:443
   headers:
     authorization: Basic MTI5Mjk0OmV5SnJJam9pT0dJNVkyWXlNak5sT1RreU9HVTVZemRrWVRNNE1ESTBZVEkzWVdKaE4yUmhNVEV3TjJJd1lpSXNJbTRpT2lKdWIzUnBabWxsY2lJc0ltbGtJam8xTnpFNU1qbDk=

service:
 pipelines:
   traces:
     receivers: [jaeger]
     processors: [batch]
     exporters: [otlp]